name: GitHub Actions Demo
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Debuk
        id: maketags
        run: |
          echo "===== $GITHUB_RUN_ID"
          echo "IMAGE_NAME=jakubowy/xmr:$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Build and push
        env:
          IMAGENAME: ${{ env.GITHUB_RUN_ID }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.IMAGE_NAME }}

